package com.aiplay.ai.actions;

import com.aiplay.ai.Json;
import com.google.gson.JsonObject;

/** One whitelisted action requested by the model (or generated by the local controller). */
public class Action {
	public static final java.util.Set<String> ALLOWED = java.util.Set.of(
			"move", "look", "attack", "jump", "sprint", "sneak", "switch_slot", "use_item",
			"interact", "drop_item", "swap_to_hotbar", "stop", "wait");

	public final String type;
	public final JsonObject args;
	public final String reason;
	/** internal = generated by the local controller (healing etc.): not gated by AI toggles, not replaced by new decisions. */
	public boolean internal;

	public Action(String type, JsonObject args, String reason) {
		this.type = type;
		this.args = args == null ? new JsonObject() : args;
		this.reason = reason == null ? "" : reason;
	}

	public static Action internal(String type, Object... kv) {
		JsonObject o = new JsonObject();
		for (int i = 0; i + 1 < kv.length; i += 2) {
			Object v = kv[i + 1];
			if (v instanceof Number n) o.addProperty((String) kv[i], n);
			else if (v instanceof Boolean b) o.addProperty((String) kv[i], b);
			else o.addProperty((String) kv[i], String.valueOf(v));
		}
		Action a = new Action(type, o, "local controller");
		a.internal = true;
		return a;
	}

	public static Action parse(JsonObject o) {
		String t = Json.str(o, "action", "").toLowerCase().trim();
		if (!ALLOWED.contains(t)) throw new IllegalArgumentException("Unknown action: '" + t + "'");
		return new Action(t, o, Json.str(o, "reason", ""));
	}

	public int i(String k, int d) { return Json.num(args, k, d); }
	public double d(String k, double dd) { return Json.dbl(args, k, dd); }
	public String s(String k, String d) { return Json.str(args, k, d); }
	public boolean b(String k, boolean d) { return Json.bool(args, k, d); }
	public boolean has(String k) { return args.has(k); }

	@Override public String toString() { return type + (args.size() > 1 ? " " + args : ""); }
}
